import { Router } from "express";
import { requireAuth } from "../middleware/auth";
import { completeSession, currentItem, profile, recordResponse, startSession } from "../services/assessmentStore";
import { diagnosticProblems } from "../services/assessmentEngine";
import { AssessmentRepository, hasPersistentBackend } from "../services/assessmentRepository";
const router = Router();
router.use(requireAuth);
const uid = (req: { userId?: string }) => req.userId ?? "demo-user";
const repo = (req: { userId?: string; authToken?: string }) => req.authToken && hasPersistentBackend(req.authToken) ? new AssessmentRepository(uid(req), req.authToken) : null;
router.get("/api/me", async (req, res) => {
  try { const persistent = repo(req); if (persistent) return res.json(await persistent.me()); const item = profile(uid(req)); return res.json({ user: { id: uid(req) }, userId: uid(req), onboarding: item?.onboarding ?? null, assessment: item ? { id: item.id, status: item.completed ? "completed" : "in_progress", completedItems: item.responses.length } : null, assessmentComplete: Boolean(item), profile: item ? { hypotheses: item.hypotheses, observations: item.observations } : null, path: item?.recommendation ? { recommendation: item.recommendation } : null, recommendation: item?.recommendation ?? null, next: item ? "path" : "onboarding" }); } catch (error) { return res.status(500).json({ error: error instanceof Error ? error.message : "Unable to load learner state" }); }
});
router.put("/api/me/onboarding", async (req, res) => { try { const persistent = repo(req); if (!persistent) return res.status(503).json({ error: "Persistent learner state is unavailable" }); return res.json(await persistent.updateOnboarding(req.body)); } catch (error) { return res.status(400).json({ error: error instanceof Error ? error.message : "Unable to save onboarding" }); } });
router.post("/api/assessments", async (req, res) => { try { const persistent = repo(req); if (persistent) { const session = await persistent.start(req.body.onboarding); return res.status(201).json({ id: session.id, status: session.completed ? "completed" : "in_progress", current: diagnosticProblems[session.responses.length] }); } const session = startSession(uid(req), req.body.onboarding); return res.status(201).json({ id: session.id, status: "in_progress", current: diagnosticProblems[0] }); } catch (error) { return res.status(400).json({ error: error instanceof Error ? error.message : "Unable to start assessment" }); } });
router.get("/api/assessments/:id/current", async (req, res) => { try { const persistent = repo(req); const current = persistent ? await persistent.current(req.params.id) : currentItem(uid(req), req.params.id); if (!current) return res.status(404).json({ error: "Assessment not found or complete" }); return res.json({ current }); } catch (error) { return res.status(404).json({ error: error instanceof Error ? error.message : "Assessment not found" }); } });
router.post("/api/assessments/:id/items/:itemId/respond", async (req, res) => { try { const persistent = repo(req); const result = persistent ? await persistent.respond(req.params.id, { ...req.body, problemSlug: req.body.problemSlug ?? req.params.itemId }) : recordResponse(uid(req), req.params.id, req.body); return res.json({ next: result.next ?? null, completedItems: result.session.responses.length }); } catch (error) { return res.status(400).json({ error: error instanceof Error ? error.message : "Invalid response" }); } });
router.post("/api/assessments/:id/complete", async (req, res) => { try { const persistent = repo(req); const result = persistent ? await persistent.complete(req.params.id) : completeSession(uid(req), req.params.id); return res.json({ profile: result.hypotheses, recommendation: result.recommendation, observations: result.observations }); } catch (error) { return res.status(400).json({ error: error instanceof Error ? error.message : "Unable to complete assessment" }); } });
router.get("/api/profile", async (req, res) => { try { const persistent = repo(req); if (persistent) { const state = await persistent.me(); if (!state.profile) return res.status(404).json({ error: "Assessment not complete" }); return res.json(state.profile); } const item = profile(uid(req)); if (!item) return res.status(404).json({ error: "Assessment not complete" }); return res.json({ hypotheses: item.hypotheses, observations: item.observations, onboarding: item.onboarding }); } catch (error) { return res.status(500).json({ error: error instanceof Error ? error.message : "Unable to load profile" }); } });
router.get("/api/path", async (req, res) => { try { const persistent = repo(req); if (persistent) { const state = await persistent.me(); if (!state.path) return res.status(404).json({ error: "Path not ready" }); return res.json(state.path); } const item = profile(uid(req)); if (!item?.recommendation) return res.status(404).json({ error: "Path not ready" }); return res.json({ recommendation: item.recommendation, items: [{ position: 1, title: item.recommendation.title, targetSkill: item.recommendation.targetSkill, reason: item.recommendation.reason, estimatedMinutes: item.recommendation.estimatedMinutes }] }); } catch (error) { return res.status(500).json({ error: error instanceof Error ? error.message : "Unable to load path" }); } });
router.get("/api/recommendations/next", async (req, res) => { const persistent = repo(req); if (persistent) { const state = await persistent.me(); if (!state.recommendation) return res.status(404).json({ error: "Recommendation not ready" }); return res.json(state.recommendation); } const item = profile(uid(req)); if (!item?.recommendation) return res.status(404).json({ error: "Recommendation not ready" }); return res.json(item.recommendation); });
export default router;
