import { randomUUID } from "node:crypto";
import { z } from "zod";
import { buildHypotheses, buildRecommendation, diagnosticProblems, generateObservations, type DiagnosticResponse, type Hypothesis, type Observation, type Recommendation, type LearningPathItem } from "./assessmentEngine";

export const onboardingSchema = z.object({ goal: z.string().min(1), timeline: z.string().min(1), availability: z.string().min(1), language: z.string().min(1), selfAssessment: z.string().optional().default(""), customGoal: z.string().optional().default("") });
export const responseSchema = z.object({ problemSlug: z.string(), sequence: z.number().int().min(1).max(3), durationSeconds: z.number().int().min(0).max(7200), result: z.enum(["solved","partial","stuck"]), hintCount: z.number().int().min(0).max(20), approach: z.string().max(4000), complexity: z.string().max(1000), dataStructure: z.string().max(200).optional(), code: z.string().max(12000).optional(), explanation: z.string().max(4000).optional() });
export type StoredSession = { id: string; userId: string; onboarding: z.infer<typeof onboardingSchema>; responses: DiagnosticResponse[]; observations: Observation[]; hypotheses: Hypothesis[]; recommendation?: Recommendation; pathItems?: LearningPathItem[]; completed: boolean; createdAt: string };
const sessions = new Map<string, StoredSession>();

export function startSession(userId: string, onboarding: unknown) { const parsed = onboardingSchema.parse(onboarding); const session: StoredSession = { id: randomUUID(), userId, onboarding: parsed, responses: [], observations: [], hypotheses: [], completed: false, createdAt: new Date().toISOString() }; sessions.set(session.id, session); return session; }
export function getSession(userId: string, id: string) { const session = sessions.get(id); if (!session || session.userId !== userId) return undefined; return session; }
export function currentItem(userId: string, id: string) { const session = getSession(userId, id); if (!session) return undefined; return diagnosticProblems[session.responses.length]; }
export function recordResponse(userId: string, id: string, input: unknown) { const session = getSession(userId, id); if (!session) throw new Error("Assessment not found"); if (session.completed) throw new Error("Assessment already completed"); const response = responseSchema.parse(input); const existing = session.responses.find((item) => item.sequence === response.sequence || item.problemSlug === response.problemSlug); if (existing) return { session, next: diagnosticProblems[session.responses.length] }; if (response.sequence !== session.responses.length + 1) throw new Error("Responses must be submitted in sequence"); session.responses.push(response); session.observations.push(...generateObservations(response)); return { session, next: diagnosticProblems[session.responses.length] }; }
export function completeSession(userId: string, id: string) { const session = getSession(userId, id); if (!session) throw new Error("Assessment not found"); if (session.completed) return session; if (session.responses.length !== diagnosticProblems.length) throw new Error("Complete all three diagnostic problems first"); session.hypotheses = buildHypotheses(session.observations); session.recommendation = buildRecommendation(session.hypotheses, session.onboarding.goal, session.onboarding.availability); session.completed = true; return session; }
export function profile(userId: string) { return [...sessions.values()].filter((item) => item.userId === userId && item.completed).sort((a,b) => b.createdAt.localeCompare(a.createdAt))[0]; }
